import test from 'node:test';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';
import {planBlurBroll,opBlurBroll} from '../src/derived-media.mjs';
const media=fileURLToPath(new URL('../package.json',import.meta.url));
function fixture(){const s={id:'screen',material_id:'m',desc:'layout:screen-recording',volume:0,source_timerange:{start:1000000,duration:8000000},target_timerange:{start:0,duration:1000000},extra_material_refs:[],common_keyframes:[{property_type:'KFTypeScaleX',keyframe_list:[{time_offset:1000000,values:[1],right_control:{x:800000,y:.1}},{time_offset:9000000,values:[1.2],left_control:{x:-800000,y:.1}}]}]};return {id:'test',duration:1000000,canvas_config:{width:1080,height:1920},materials:{videos:[{id:'m',type:'video',path:media,width:1080,height:1920,duration:10000000},{id:'face-m',type:'video',path:media,width:1080,height:1920,duration:1000000}],speeds:[]},tracks:[{type:'video',flag:0,segments:[]},{type:'video',flag:2,segments:[s]},{type:'video',flag:2,segments:[{...structuredClone(s),id:'face',material_id:'face-m',desc:'scene 1',volume:1,source_timerange:{start:0,duration:1000000},common_keyframes:[]}]}]};}
const context={projectDir:'/durable/project',dryRun:true};
test('blur gates face, speed and ephemeral paths before rendering',()=>{assert.throws(()=>planBlurBroll(fixture(),{segment:'face'},context));const d=fixture();d.tracks[1].segments[0].source_timerange.duration=1000000;assert.throws(()=>planBlurBroll(d,{segment:'screen'},context));assert.throws(()=>planBlurBroll(fixture(),{segment:'screen'},{projectDir:'/tmp/project'}));});
test('derivative preserves slot and geometry, records recoverable origin, and resets native speed',()=>{const d=fixture(),before=structuredClone(d.tracks[2]);const result=opBlurBroll(d,{segment:'screen',__seed:'test'},context);assert.equal(result.playbackSpeed,1);const s=d.tracks[1].segments[0],m=d.materials.videos.find(m=>m.id===s.material_id);assert.equal(m.derived_from_path,media);assert.equal(m.derived_from_offset,1);assert.deepEqual(s.target_timerange,{start:0,duration:1000000});assert.deepEqual(s.source_timerange,{start:0,duration:1000000});assert.equal(s.speed,1);assert.equal(s.common_keyframes[0].keyframe_list[0].right_control.x,100000);assert.deepEqual(d.tracks[2],before);});
